stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - ./gradlew assemble

test:
  stage: test
  script:
    - ./gradlew test

deploy:
  stage: deploy
  script:
    - ./gradlew bootJar
  artifacts:
    paths:
      - TourGuide/build/libs/*.jar
